services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    env_file:
      - .env
    restart: unless-stopped

volumes:
  influxdb2-data:
  influxdb2-config:
